### ISSUE TITLE
Some web links is not found

### ISSUE THREAD

**Issue by edidada** [hujiaweibujidao/AndroidInterviews#3]
Where I visit website like https://www.haomwei.com/technology/maupassant-hexo.html
404 not found

**Comment by hujiaweibujidao** [comment]
@edidada Actually the web link [https://www.haomwei.com/technology/maupassant-hexo.html](https://www.haomwei.com/technology/maupassant-hexo.html) is OK, btw, it's nothing about the topic of this repository, so just forget about it.
